# Generated by Django 4.1.5 on 2023-02-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='baner',
            new_name='banner',
        ),
    ]
