# Generated by Django 4.1.5 on 2023-02-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='article',
            new_name='post',
        ),
    ]
